# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: virtual_stick.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'virtual_stick.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13virtual_stick.proto\x12\x10\x64ji.flightrecord\"\xe4\x01\n\x1dVirtualStickFlightControlData\x12\r\n\x05pitch\x18\x01 \x01(\x02\x12\x0c\n\x04roll\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x12\x19\n\x11vertical_throttle\x18\x04 \x01(\x02\x12\x1d\n\x15vertical_control_mode\x18\x05 \x01(\x05\x12\x1f\n\x17roll_pitch_control_mode\x18\x06 \x01(\x05\x12\x18\n\x10yaw_control_mode\x18\x07 \x01(\x05\x12$\n\x1croll_pitch_coordinate_system\x18\x08 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'virtual_stick_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIRTUALSTICKFLIGHTCONTROLDATA']._serialized_start=42
  _globals['_VIRTUALSTICKFLIGHTCONTROLDATA']._serialized_end=270
# @@protoc_insertion_point(module_scope)
